version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00" # UTC
    #labels:
    #  - "domain: deps"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "bruceg"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "bruceg"
    #labels:
    #  - "domain: ci"
    commit-message:
      prefix: "chore(ci)"
