[package]
name = "rust-license-tool"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Datadog, Inc."]

[profile.release]
strip = true

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.15"
clap = { version = "4.2.7", default-features = false, features = ["derive", "std", "help"] }
csv = "1.2.1"
hex = "0.4.3"
once_cell = "1.17.1"
regex = "1.8.3"
serde = "1.0"
serde_json = "1.0"
toml = "0.7"
url = "2.3.1"
