[package]
name = "dd-rust-license-tool"
description = "A tool for creating the `LICENSE-3rdparty.csv` file for DataDog open-source Rust projects."
homepage = "https://github.com/DataDog/rust-license-tool"
repository = "https://github.com/DataDog/rust-license-tool"
readme = "README.md"
version = "1.0.2"
edition = "2021"
license = "MIT"
authors = ["Datadog, Inc."]
categories = ["command-line-utilities", "development-tools"]
keywords = ["datadog", "license", "3rdparty"]

[profile.release]
strip = true

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.18"
clap = { version = "4.5.1", default-features = false, features = ["derive", "std", "help"] }
csv = "1.3.0"
hex = "0.4.3"
once_cell = "1.19.0"
regex = "1.10.3"
serde = "1.0"
serde_json = "1.0"
toml = "0.8"
url = "2.5.0"
