[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    #"RUSTSEC-0000-0000",
]

[bans]
multiple-versions = "deny"
skip = [
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    #"Zlib"
]
