[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "deny"
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
unlicensed = "deny"
default = "deny"
copyleft = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib"
]
